import {Agent} from '../types';

export const agentList:Agent[] = [
  { name: 'Brimstone' },
  { name: 'Viper' },
  { name: 'Omen' },
  { name: 'Killjoy' },
  { name: 'Cypher' },
  { name: 'Sova' },
  { name: 'Sage' },
  { name: 'Phoenix' },
  { name: 'Jett' },
  { name: 'Reyna' },
  { name: 'Raze' },
  { name: 'Breach' },
  { name: 'Skye' },
  { name: 'Yoru' },
  { name: 'Astra' },
  { name: 'KAY/O' },
  { name: 'Chamber' },
  { name: 'Neon' },
  { name: 'Fade' },
  { name: 'Harbor' },
  { name: 'Gekko' },
  { name: 'Deadlock' },
  { name: 'Iso' },
];